version: '3.9'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - myvol:/var/lib/mysql
    networks:
      - mynet
    environment:
      - MYSQL_ROOT_PASSWORD=SecurePass@123
      - MYSQL_DATABASE=wordpressdb

  website:
    image: wordpress:latest
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - mynet
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=SecurePass@123
      - WORDPRESS_DB_NAME=wordpressdb

networks:
  mynet:
    driver: bridge

volumes:
  myvol:
